# --- Created by Slick DDL
# To stop Slick DDL generation, remove this comment and start using Evolutions

# --- !Ups

create table "ACCOUNT" ("id" VARCHAR NOT NULL PRIMARY KEY,"status" INTEGER);
create table "COMPANY" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"name" VARCHAR NOT NULL,"website" VARCHAR NOT NULL,"edition" VARCHAR NOT NULL,"uuid" VARCHAR NOT NULL);
create table "USER" ("id" BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) NOT NULL PRIMARY KEY,"email" VARCHAR NOT NULL,"firstName" VARCHAR NOT NULL,"lastName" VARCHAR NOT NULL,"openId" VARCHAR NOT NULL,"companyId" BIGINT,"creator" BOOLEAN);

# --- !Downs

drop table "USER";
drop table "COMPANY";
drop table "ACCOUNT";

